name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker-actions:action
  run-container:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run Container
        run: docker run -dp 3000:3000 --name docker-action docker-actions:action
